[package]
name = "bm-infra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
figment = { workspace = true }
fred = { workspace = true, optional = true }
futures-lite = "2"
lapin = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, optional = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
rust_decimal = { workspace = true }
bm-types = { workspace = true }
bm-domain = { workspace = true }

[features]
default = ["memory", "redis", "mysql", "rabbit"]
memory = []
redis = ["dep:fred"]
mysql = ["dep:sqlx"]
rabbit = ["dep:lapin"]
