#
# ** 此文件由工具自动生成，请勿手工编辑 **
#

# Docker 目标环境的默认 Kibana 配置
server.host: "0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
i18n.locale: "zh-CN"
